apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: jaeger-query
spec:
  rules:
    - host: jaeger.nuc
      http:
        paths:
          - path: /
            backend:
              serviceName: jaeger-query
              servicePort: 16686
            
