apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: jaeger-example-hotrod
spec:
  rules:
    - host: jaeger-example-hotrod.nuc
      http:
        paths:
          - path: /
            backend:
              serviceName: jaeger-example-hotrod
              servicePort: 8080
